# Generated by Django 3.0 on 2020-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, null=True, verbose_name='Производитель')),
                ('model_of_auto', models.CharField(max_length=40, null=True, verbose_name='Модель авто')),
                ('year_of_issue', models.IntegerField(default=2020, null=True, verbose_name='Год выпуска')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'робот')], null=True, verbose_name='Коробка передач')),
                ('colour', models.CharField(max_length=20, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
